### ISSUE TITLE
Investigate yelp repository update issue

### ISSUE THREAD

**Issue by fbiville** [neo4j-contrib/sandbox-code-updater#52]
`https://github.com/neo4j-graph-examples/yelp.git`, a currently private repository, seems to cause the CI to consistently fail:

```java
Caused by: java.io.IOException: 1 of the updates failed, see details below
---
 - Update for sandbox https://github.com/neo4j-graph-examples/yelp.git failed with the following error:
java.io.IOException: org.eclipse.jgit.api.errors.InvalidRemoteException: Invalid remote: origin
---

	at com.neo4j.sandbox.updater.BatchUpdater.updateBatch(BatchUpdater.java:93) ~[classes/:na]
	at com.neo4j.sandbox.Main.run(Main.java:19) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791) ~[spring-boot-2.5.2.jar:2.5.2]
	... 5 common frames omitted

```

**Comment by fbiville** [comment]
It turns out that the Personal Access Token for @neo4j-oss-build only included the `public_repo` scope.
The configuration has been fixed now.
